micronaut:
  application:
    name: vote-backend
  # expose Swagger OpenAPI
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

jackson:
  bean-introspection-module: true

datasources:
  default:
#    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password: ''
#    dialect: H2
    url: jdbc:postgresql://localhost:5432/vote?ssl=false
    driverClassName: org.postgresql.Driver
    username: vote
    password: gJnUwvJ&EbeP
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

# expose for debug and monitoring
endpoints:
  all.path: /m
  flyway:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false

#
#security:
#  enabled: true
#  endpoints:
#    login:
#      enabled: true
#    oauth:
#      enabled: true
#  token:
#    jwt:
#      enabled: true
#      signatures:
#        secret:
#          generator:
#            secret: "${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"

# alternative way to specify log level
logger:
  levels:
    foo.bar: ERROR