micronaut:
  application:
    name: vote-backend
  # expose Swagger OpenAPI
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

  security:
    enabled: false
    authentication: bearer
    redirect:
      forbidden: true


#    basic-auth:
#      enabled: true
#    authentication: idtoken
#    oauth2:
#      clients:
#        google:
#          client-secret: <<your client secret>>
#          client-id: <<your client id>>
#          openid:
#            issuer: https://accounts.google.com

jackson:
  bean-introspection-module: true
  serialization:
    # Configure Jackson to represent Instant as human readable dates rather than epoch second.nanosecond
    write-dates-as-timestamps: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/vote?ssl=false
    driverClassName: org.postgresql.Driver
    username: vote
    password: gJnUwvJ&EbeP
    dialect: POSTGRES

# database migration
flyway:
  datasources:
    default:
      enabled: true
      locations: classpath:db/migration

# expose /m path for debug and monitoring
endpoints:
  all.path: /m
  flyway:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: false
  info:
    enabled: true
    sensitive: false
  loggers:
    enabled: true

# alternative way to specify log level
logger:
  levels:
    io:
      micronaut:
        security:
          authentication: DEBUG