datasources:
  default:
    url: jdbc:postgresql:///votedb?cloudSqlInstance=vote-301515:europe-west4:votedb&socketFactory=com.google.cloud.sql.postgres.SocketFactory&
    driverClassName: org.postgresql.Driver
    username: votedb_user
    password: gJnUwvJ&EbeP
    dialect: POSTGRES